title: File
columns:
  main:
    width: 1/1
    sections:
      content:
        type: fields
        fields:
          tags:
            label: Tags
            type: checkboxes
            width: 1/2
            options: query
            query:
              fetch: site.find('home').words.split
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value }}"
          text:
            label: Caption
            width: 1/2
            type: textarea
            size: medium
          authors:
            # type: text
            # size: medium
            label: Authors
            width: 1/2
            type: checkboxes
            options: query
            query:
              fetch: site.find('home').participants.split
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value }}"
          vimeo_id:
            label: Vimeo ID (for screenshots only)
            width: 1/2
            type: text
            size: medium
